# Generated by Django 5.2.10 on 2026-01-19 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=100)),
                ('arrondissement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=15)),
                ('parcelles_info', models.TextField(verbose_name='Localisation des parcelles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField(verbose_name='Quantité (kg)')),
                ('date_recolte', models.DateField()),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producteur')),
                ('type_culture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.culture')),
            ],
        ),
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('capacite_max', models.FloatField(verbose_name='Capacité totale (kg)')),
                ('stock_actuel', models.FloatField(default=0)),
                ('seuil_alerte', models.FloatField(verbose_name="Seuil d'alerte minimum (kg)")),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.zone')),
            ],
        ),
    ]
