# Generated by Django 5.2.10 on 2026-01-19 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepot',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Magasinier responsable'),
        ),
        migrations.AlterField(
            model_name='entrepot',
            name='stock_actuel',
            field=models.FloatField(default=0, verbose_name='Stock actuel (kg)'),
        ),
    ]
