# Generated by Django 5.2.10 on 2026-01-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_entrepot_responsable_alter_entrepot_stock_actuel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Zone géographique'},
        ),
        migrations.AddField(
            model_name='zone',
            name='village',
            field=models.CharField(default='Non renseigné', help_text='Ex: Kpébié, Fidjrossè, etc.', max_length=100, verbose_name='Village/Quartier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zone',
            name='arrondissement',
            field=models.CharField(max_length=100, verbose_name='Arrondissement'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='commune',
            field=models.CharField(max_length=100, verbose_name='Commune'),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('commune', 'arrondissement', 'village')},
        ),
    ]
