# Generated by Django 5.2.10 on 2026-01-20 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_zone_options_zone_village_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recolte',
            name='entrepot_destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.entrepot', verbose_name='Dépôt vers'),
        ),
        migrations.AddField(
            model_name='recolte',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('RECU', 'Reçu au magasin')], default='EN_ATTENTE', max_length=20),
        ),
    ]
