# Generated by Django 5.2.10 on 2026-01-21 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_recolte_entrepot_destination_recolte_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200, verbose_name='Entreprise Cliente')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité (kg)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expedition', models.DateTimeField(blank=True, null=True, verbose_name='Date effective de sortie')),
                ('statut', models.CharField(choices=[('PROGRAMME', 'Programmé (En attente)'), ('EXPEDIE', 'Expédié (Sorti du stock)'), ('ANNULE', 'Annulé')], default='PROGRAMME', max_length=20)),
                ('confirme_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties_confirmees', to=settings.AUTH_USER_MODEL)),
                ('entrepot_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entrepot', verbose_name="Entrepôt d'origine")),
                ('ordonne_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties_ordonnees', to=settings.AUTH_USER_MODEL)),
                ('type_culture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.culture', verbose_name='Produit / Culture')),
            ],
            options={
                'verbose_name': 'Livraison / Sortie',
            },
        ),
    ]
